import Head from 'next/head'
import { useRouter } from "next/router"
import { useRef } from 'react'
import Tippy from '@tippyjs/react';
import 'tippy.js/dist/tippy.css';

import { DropdownApp, DropdownAccount } from "../components/dropdown"
import { Footer } from "../components/footer"

export default function Home() {
  const router = useRouter()
  const searchInputRef = useRef(null)

  const handleSearch = (e) => {
    e.preventDefault()
    const term = searchInputRef.current.value

    if (!term) return

    router.push(`/search?term=${term}`)
  }

  return (
    <div className="flex flex-col h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.svg" />
      </Head>

      {/* Header */}
      <header className="w-full">
        <div className="flex justify-end items-center p-2 space-x-2">
          <div className="text-sm hover:underline cursor-pointer tracking-tight">
            <a href="https://mail.google.com/">Gmail</a>
          </div>
          <div className="text-sm hover:underline cursor-pointer tracking-tight">
            <a href="https://www.google.com.ar/imghp?hl=es-419&ogbl">Imagenes</a>
          </div>
          <div>
            <Tippy
              content={<div>Google Apps</div>}
              placement={"bottom"}
              arrow={"none"}
              delay={"400"}
            >
              <div className="p-2 hover:bg-gray-200 cursor-pointer rounded-full">
                <DropdownApp />
              </div>
            </Tippy>
          </div>
          <div>
            <Tippy
              content={<div className="flex flex-col"><h1>Cuenta de Google</h1><h1 className="text-gray-400">Name</h1><h1 className="text-gray-400">Example@gmail.com</h1></div>}
              placement={"bottom"}
              arrow={"none"}
              delay={"400"}
            >
              <div className="p-2 cursor-pointer hover:bg-gray-200 rounded-full">
                <DropdownAccount />
              </div>
            </Tippy>
          </div>
        </div>
      </header>
      {/* Body */}
      <main className="w-full flex flex-grow justify-center items-center mb-20">
        <div className="flex flex-col xl:w-4/12 lg:w-6/12 md:w-8/12 sm:w-10/12 w-10/12">
          {/* Logo */}
          <div className="flex items-center justify-center">
            <img src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"></img>
          </div>
          {/* Search */}
          <div className="flex flex-row border p-2 pl-4 pr-4 mt-10 items-center border-gray-200 rounded-full hover:shadow-md">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
            </svg>
            <input
              type="search"
              className="pl-2 focus:outline-none w-full"
              ref={searchInputRef}
            ></input>
            <Tippy
              content={<div>Búsqueda por voz</div>}
              placement={"bottom"}
            >
              <div>
                <svg class="h-6 w-6 cursor-pointer" focusable="false" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path fill="#4285f4" d="m12 15c1.66 0 3-1.31 3-2.97v-7.02c0-1.66-1.34-3.01-3-3.01s-3 1.34-3 3.01v7.02c0 1.66 1.34 2.97 3 2.97z"></path><path fill="#34a853" d="m11 18.08h2v3.92h-2z"></path><path fill="#fbbc05" d="m7.05 16.87c-1.27-1.33-2.05-2.83-2.05-4.87h2c0 1.45 0.56 2.42 1.47 3.38v0.32l-1.15 1.18z"></path><path fill="#ea4335" d="m12 16.93a4.97 5.25 0 0 1 -3.54 -1.55l-1.41 1.49c1.26 1.34 3.02 2.13 4.95 2.13 3.87 0 6.99-2.92 6.99-7h-1.99c0 2.92-2.24 4.93-5 4.93z"></path></svg>
              </div>
            </Tippy>
          </div>
          {/* Buttons */}
          <div className="space-x-5 flex justify-center mt-2">
            <button
              className="bg-gray-50 tracking-tight p-2 mt-5 rounded-md text-sm focus:outline-none hover:shadow"
              onClick={handleSearch}
            >
              Buscar con Google</button>
            <a href="https://www.google.com/doodles" className="bg-gray-50 tracking-tight p-2 mt-5 rounded-md text-sm focus:outline-none hover:shadow">Me siento con suerte</a>
          </div>
          <div className="flex flex-col items-center">
            <h1 className="text-sm mt-5 tracking-tight">Ofrecido por Google en: <a className="hover:underline cursor-pointer text-blue-800">English</a></h1>
          </div>
        </div>
      </main>
      <Footer />

    </div >
  )
}
