import Head from "next/head"
import { useRouter } from "next/router"
import { API_KEY, CONTEXT_KEY } from "../keys"

import { FooterSearch } from "../components/footer"
import { Header } from "../components/header"

function search({ results }) {
    const router = useRouter()
    console.log(results)
    return (
        <div className="h-screen">
            <Head>
                <title>{router.query.term} - Buscar con Google</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/icon.svg" />
            </Head>

            <Header />
            <div className=" h-4/6">

            </div>
            <FooterSearch />
        </div>
    )
}

export default search

export async function getServerSideProps(context) {
    const useDummyData = false

    const data = await fetch(
        `https://www.googleapis.com/customsearch/v1?key=${API_KEY}&cx=${CONTEXT_KEY}&q=${context.query.term}`
    ).then(resp => resp.json())

    return {
        props: {
            results: data
        }
    }
}
//No functional for now